id: I8BBA1CDB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:28:12+00:00'
last_modified: '2022-06-07T12:39:24.777694+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29978
  title: རྩིས་གཞུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E1BB:
      image_group_id: I5721
      title: ''
      total_pages: 358
      order: 1
      base_file: E1BB.txt
    4B7B:
      image_group_id: I5722
      title: ''
      total_pages: 564
      order: 2
      base_file: 4B7B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
